version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secure1111!
    volumes:
      - data:/data
  python:
    build: .
    command: python app.py
    volumes:
      - .:/app
    working_dir: /app
    links:
      - neo4j
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
volumes:
  data:
