version: '3.7'
services:
    server:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env

    python:
        build: .
        command: python app.py
        volumes:
            - .:/app
        working_dir: /app

    localstack:
        image: localstack/localstack
        ports:
            - "4566:4566"
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
        volumes:
            - localstack:/var/lib/localstack

    postgres:
        image: postgres:13.3
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=dagster
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
        driver: local
    localstack:
        driver: local
